# Generated by Django 4.1.3 on 2022-11-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('foto_bin', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('telefone', models.BigIntegerField()),
                ('morada', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegEquipamento',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_equip', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reserva_inicio', models.DateField()),
                ('reserva_fim', models.DateField()),
                ('hotel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='etar.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoEquip',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medicao', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=255)),
                ('regEquipamento', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='etar.regequipamento')),
            ],
        ),
    ]
