# Generated by Django 4.1.3 on 2022-12-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('foto_bin', models.BinaryField()),
                ('tipo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('telefone', models.BigIntegerField()),
                ('morada', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoEquip',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medicao', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegEquipamento',
            fields=[
                ('medicaoequip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etar.medicaoequip')),
                ('nome_equip', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=('etar.medicaoequip',),
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('hotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etar.hotel')),
                ('reserva_inicio', models.DateField()),
                ('reserva_fim', models.DateField()),
            ],
            bases=('etar.hotel',),
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etar.foto')),
                ('regEquipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etar.regequipamento')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etar.obra'),
        ),
    ]
