# Generated by Django 4.1.3 on 2022-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto_bin',
            field=models.BinaryField(),
        ),
    ]
