version: '3.8'
services:
  db:
    container_name: database
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gp_whiskey
      TZ: Europe/Lisbon
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # tail -f /dev/null
    volumes:
      - ./backend/gp_whiskey:/backend
      - ./backend/requirements.txt:/backend/requirements.txt
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      - docker=true
    links:
      - db
    depends_on:
      - db
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./frontend # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - "/etc/timezone:/etc/timezone:ro"  
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:8080/
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=dev
      - TZ=Europe/Lisbon
    restart: always

volumes:
  postgres_data:
