version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gp_whiskey
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
  web:
    build: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=gp_whiskey
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    depends_on:
      - db