version: '3.8'
services:
  db:
    container_name: database
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=gp_whiskey
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    restart: always
  web:
    container_name: backend
    build:
      context: ./backend # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # tail -f /dev/null
    volumes:
      - ./backend/gp_whiskey:/app
      - ./backend/requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    links:
      - db
    depends_on:
      - db
volumes:
  postgres_data: