# Generated by Django 4.1.2 on 2022-12-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_carro_fornecedor_fornecedorobra_equipamento'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('mail', models.CharField(max_length=512)),
                ('publico', models.BooleanField(default=False)),
                ('localizacao', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RecursosHumanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especializacao', models.CharField(max_length=512)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.fornecedor')),
            ],
        ),
    ]
