# Generated by Django 4.1.3 on 2022-12-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0004_rename_localizacao_cliente_morada_cliente_arquivado_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="recursoshumanos",
            old_name="fornecedor_id",
            new_name="fornecedor",
        ),
    ]
