# Generated by Django 4.1.3 on 2023-01-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='localizacao',
        ),
    ]
