# Generated by Django 4.1.5 on 2023-01-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='matricula',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
