# Generated by Django 4.1.5 on 2023-02-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='obra',
        #     name='arquivado',
        #     field=models.BooleanField(default=False),
        # ),
    ]
