# Generated by Django 4.1.5 on 2023-02-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_obra_arquivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
