# Generated by Django 4.1.5 on 2023-01-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_remove_obra_funcionarios_alter_obra_data_conclusao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='obra',
        ),
    ]
