# Generated by Django 4.1.3 on 2022-12-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_obra_restaurantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='restaurantes',
        ),
    ]
