# Generated by Django 4.1.5 on 2023-02-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_reserva_arquivado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
