# Generated by Django 4.1.5 on 2023-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_hotel_obras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='obras',
        ),
        migrations.AddField(
            model_name='hotel',
            name='obras',
            field=models.ManyToManyField(through='constructions.ReservaHotel', to='constructions.obra'),
        ),
    ]
