# Generated by Django 4.1.3 on 2022-12-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_carro_fornecedor_fornecedorobra_equipamento'),
        ('constructions', '0003_remove_obra_restaurantes'),
    ]

    operations = [
    ]
