# Generated by Django 4.1.5 on 2023-01-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_remove_hotel_obra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservaHotel',
            new_name='Reserva',
        ),
    ]
