# Generated by Django 4.1.5 on 2023-02-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0004_delete_equipamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegEquipamento',
            new_name='Equipamento',
        ),
    ]
