# Generated by Django 4.1.3 on 2022-12-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_fornecedor_recursoshumanos_fornecedor_id'),
        ('constructions', '0004_merge_20221203_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='fornecedor',
            new_name='fornecedor_id',
        ),
        migrations.AddField(
            model_name='carro',
            name='obras',
            field=models.ManyToManyField(to='constructions.obra'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='obras',
            field=models.ManyToManyField(to='constructions.obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='cliente_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.cliente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FornecedorObra',
        ),
    ]
