# Generated by Django 4.1.5 on 2023-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0004_alter_hotel_obras'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='hoteis',
            field=models.ManyToManyField(to='constructions.hotel'),
        ),
    ]
