# Generated by Django 4.1.5 on 2023-01-31 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0004_rename_reservahotel_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='obra',
            field=models.ManyToManyField(through='constructions.Reserva', to='constructions.obra'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='constructions.hotel'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='constructions.obra'),
        ),
    ]
