# Generated by Django 4.1.5 on 2023-01-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0005_hotel_obra_alter_reserva_hotel_alter_reserva_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='nr_obra',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='transportadora',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='regequipamento',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
