# Generated by Django 4.1.3 on 2022-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0007_alter_obra_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
    ]
