# Generated by Django 4.1.4 on 2022-12-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0007_alter_obra_cliente_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="medicaoequip",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
