# Generated by Django 4.1.2 on 2022-12-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=512)),
                ('marca', models.CharField(max_length=512)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('seguradora', models.CharField(max_length=512)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('telefone', models.BigIntegerField()),
                ('mail', models.CharField(max_length=512)),
                ('morada', models.CharField(max_length=512)),
                ('localizacao', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.fornecedor')),
                ('obra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.fornecedor')),
            ],
        ),
    ]
