# Generated by Django 4.1.3 on 2022-12-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0005_rename_fornecedor_equipamento_fornecedor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('foto_bin', models.BinaryField()),
                ('tipo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('telefone', models.BigIntegerField()),
                ('morada', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='constructions.obra')),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoEquip',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medicao', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegEquipamento',
            fields=[
                ('medicaoequip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructions.medicaoequip')),
                ('nome_equip', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=('constructions.medicaoequip',),
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('hotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructions.hotel')),
                ('reserva_inicio', models.DateField()),
                ('reserva_fim', models.DateField()),
            ],
            bases=('constructions.hotel',),
        ),
    ]
