# Generated by Django 4.1.3 on 2022-12-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_rename_localizacao_cliente_morada_cliente_arquivado_and_more'),
        ('constructions', '0006_foto_hotel_medicaoequip_regequipamento_reservahotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administration.cliente'),
        ),
    ]
