# Generated by Django 4.1.3 on 2022-12-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_rename_fornecedor_id_recursoshumanos_fornecedor"),
        ("constructions", "0007_alter_obra_cliente_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gastosextra",
            old_name="obra_id",
            new_name="obra",
        ),
        migrations.RenameField(
            model_name="obra",
            old_name="cliente_id",
            new_name="cliente",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="obra",
        ),
        migrations.RemoveField(
            model_name="regequipamento",
            name="medicaoequip_ptr",
        ),
        migrations.AddField(
            model_name="foto",
            name="funcionario",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.funcionario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foto",
            name="obra",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="constructions.obra",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicaoequip",
            name="obra",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="constructions.obra",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicaoequip",
            name="reg_equipamento",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="constructions.regequipamento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regequipamento",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservahotel",
            name="hotel",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="constructions.hotel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservahotel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservahotel",
            name="obra",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="constructions.obra",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="foto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="medicaoequip",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicaoequip",
            unique_together={("obra", "reg_equipamento")},
        ),
        migrations.AlterUniqueTogether(
            name="reservahotel",
            unique_together={("obra", "hotel")},
        ),
        migrations.RemoveField(
            model_name="reservahotel",
            name="hotel_ptr",
        ),
    ]
