# Generated by Django 4.1.3 on 2022-12-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0008_rename_obra_id_gastosextra_obra_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicaoequip",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reservahotel",
            unique_together=set(),
        ),
    ]
