# Generated by Django 4.1.3 on 2022-12-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0009_alter_medicaoequip_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipamento",
            old_name="fornecedor_id",
            new_name="fornecedor",
        ),
    ]
