# Generated by Django 4.1.3 on 2022-12-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0010_rename_fornecedor_id_equipamento_fornecedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicaoequip",
            name="reg_equipamento",
        ),
    ]
