# Generated by Django 4.1.3 on 2022-12-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTransfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='report_bin',
            field=models.CharField(max_length=2732),
        ),
    ]
