# Generated by Django 4.1.4 on 2022-12-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_rename_mail_cliente_email_and_more"),
        ("fileTransfer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relatorio",
            old_name="obra_id",
            new_name="obra",
        ),
        migrations.AddField(
            model_name="relatorio",
            name="funcionario",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.funcionario",
            ),
            preserve_default=False,
        ),
    ]
