# Generated by Django 4.1.3 on 2022-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTransfer', '0002_alter_relatorio_report_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='nome',
            field=models.CharField(default='teste', max_length=512),
            preserve_default=False,
        ),
    ]
