# Generated by Django 4.1.3 on 2022-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTransfer', '0003_relatorio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='report_bin',
            field=models.BinaryField(),
        ),
    ]
