# Generated by Django 4.1.3 on 2022-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTransfer', '0004_alter_relatorio_report_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='report_bin',
            field=models.CharField(max_length=2732),
        ),
    ]
