# Generated by Django 4.1.3 on 2022-12-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_rename_fornecedor_id_recursoshumanos_fornecedor"),
        ("fileTransfer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relatorio",
            old_name="obra_id",
            new_name="obra",
        ),
        migrations.AddField(
            model_name="relatorio",
            name="funcionario",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.funcionario",
            ),
            preserve_default=False,
        ),
    ]
