# Generated by Django 4.1.3 on 2022-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('cargo', models.CharField(max_length=512)),
                ('seguro_saude', models.CharField(max_length=512)),
                ('data_inicio', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obras', models.ManyToManyField(to='constructions.obra')),
            ],
        ),
    ]
