# Generated by Django 4.1.4 on 2022-12-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("constructions", "0001_initial"),
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recursoshumanos",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="constructions.fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="obras",
            field=models.ManyToManyField(to="constructions.obra"),
        ),
    ]
