# Generated by Django 4.1.5 on 2023-01-31 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_conclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
