# Generated by Django 4.1.3 on 2023-01-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='mail',
        ),
    ]
