# Generated by Django 4.1.3 on 2022-12-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_cliente_recursoshumanos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursoshumanos',
            old_name='fornecedor',
            new_name='fornecedor_id',
        ),
    ]
