# Generated by Django 4.1.5 on 2023-02-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_name',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_conclusao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
