# Generated by Django 4.1.3 on 2023-01-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_email_cliente_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='obras',
        ),
    ]
