# Generated by Django 4.1.5 on 2023-02-02 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_funcionario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_conclusao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
