# Generated by Django 4.1.3 on 2022-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_fornecedor_recursoshumanos_fornecedor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='localizacao',
            new_name='morada',
        ),
        migrations.AddField(
            model_name='cliente',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
