# Generated by Django 4.1.5 on 2023-02-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_funcionario_data_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_conclusao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
