name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  USE_REMOTE_DB: false
  LOCAL_DATABASE_HOST: localhost
  LOCAL_DATABASE_NAME: gp_whiskey
  LOCAL_DATABASE_USER: postgres
  LOCAL_DATABASE_PASSWORD: postgres
  SECRET_KEY: '0x-et3rr12rh+jzlthsngdoszng5y#z(+3w%$(nufvzssrze06'
  REMOTE_DATABASE_PROD_NAME: gp_whiskey_prod
  REMOTE_DATABASE_NAME: gp_whiskey
  REMOTE_DATABASE_HOST: server
  REMOTE_DATABASE_PASSWORD: pwd
  REMOTE_DATABASE_USER: postgres
  DATABASE_PORT: 5432

  
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        pwd
        ls -la
        python backend/gp_whiskey/manage.py test
