name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  USE_REMOTE_DB: false
  LOCAL_DATABASE_HOST: localhost
  LOCAL_DATABASE_NAMEL: gp_whiskey
  LOCAL_DATABASE_USER: postgres
  LOCAL_DATABASE_PASSWORD: postgres
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pwd
        ls -la
        python gp_whiskey/manage.py test
